Repository senaite/senaite.sync, pull requests merged in 2018-05, with the labels that each got.

#42 New Advanced Configuration Options
  CHANGES.rst
  src/senaite/sync/browser/add.py
  src/senaite/sync/browser/configure.zcml
  src/senaite/sync/browser/templates/add.pt
  src/senaite/sync/browser/templates/sync.pt
  src/senaite/sync/browser/views.py
  src/senaite/sync/complementstep.py
  src/senaite/sync/fetchstep.py
  src/senaite/sync/importstep.py
  src/senaite/sync/souphandler.py
  src/senaite/sync/syncstep.py
  src/senaite/sync/utils.py
Labels: enhancement

#43 Querying last modified objects directly from 'uid_catalog'
  CHANGES.rst
  src/senaite/sync/complementstep.py
  src/senaite/sync/configure.zcml
  src/senaite/sync/profiles/default/senaite.sync.txt
  src/senaite/sync/setuphandlers.py
  src/senaite/sync/upgrade/v01_00_000.py
  src/senaite/sync/utils.py
Labels: enhancement

#44 Advanced Configuration: 'Read-Only' Portal Types
  CHANGES.rst
  src/senaite/sync/browser/add.py
  src/senaite/sync/browser/templates/add.pt
  src/senaite/sync/browser/views.py
  src/senaite/sync/fetchstep.py
  src/senaite/sync/importstep.py
  src/senaite/sync/syncstep.py
Labels: enhancement

#45 Error while Fetching Missing Parents
  CHANGES.rst
  src/senaite/sync/syncstep.py
Labels: bug

#47 Refactoring
  src/senaite/sync/browser/add.py
  src/senaite/sync/browser/templates/add.pt
  src/senaite/sync/browser/templates/sync.pt
  src/senaite/sync/browser/views.py
  src/senaite/sync/complementstep.py
  src/senaite/sync/fetchstep.py
  src/senaite/sync/importstep.py
  src/senaite/sync/syncstep.py
Labels: enhancement

#41 Pre-release fixes and corrections
  CONTRIBUTORS.rst
  README.rst
  buildout.cfg
  src/senaite/__init__.py
  src/senaite/sync/__init__.py
  src/senaite/sync/browser/__init__.py
  src/senaite/sync/browser/autosync.py
  src/senaite/sync/browser/interfaces.py
  src/senaite/sync/browser/views.py
  src/senaite/sync/complementstep.py
  src/senaite/sync/config.py
  src/senaite/sync/fetchstep.py
  src/senaite/sync/fieldmanagers.py
  src/senaite/sync/importstep.py
  src/senaite/sync/souphandler.py
  src/senaite/sync/syncerror.py
  src/senaite/sync/syncstep.py
  src/senaite/sync/upgrade/__init__.py
  src/senaite/sync/upgrade/v01_00_000.py
  src/senaite/sync/utils.py
  templates/write_code_headers.py.in
  templates/write_contributors.py.in
Labels: enhancement

#48 Auto Synchronization
  CHANGES.rst
  src/senaite/sync/browser/add.py
  src/senaite/sync/browser/autosync.py
  src/senaite/sync/browser/configure.zcml
  src/senaite/sync/browser/templates/add.pt
  src/senaite/sync/browser/templates/edit_sync_domains.pt
  src/senaite/sync/browser/templates/sync.pt
  src/senaite/sync/browser/views.py
  src/senaite/sync/importstep.py
  src/senaite/sync/updatestep.py
Labels: bug, enhancement

#49 More User Friendly Interface
  src/senaite/sync/browser/configure.zcml
  src/senaite/sync/browser/templates/add.pt
  src/senaite/sync/browser/templates/content_types.pt
  src/senaite/sync/browser/views.py
  src/senaite/sync/profiles/default/actions.xml
Labels: enhancement
