Repository senaite/senaite.sync, pull requests merged in 2018-03, with the labels that each got.

#27 Analyses of Worksheets are not in proper Workflow State.
  src/senaite/sync/importstep.py
  src/senaite/sync/utils.py
Labels: bug

#28 Users do not belong to any user group after Sync
  src/senaite/sync/importstep.py
Labels: bug, enhancement

#32 Added in log the estimated date of the end of data import and % of completion
  src/senaite/sync/fetchstep.py
  src/senaite/sync/importstep.py
  src/senaite/sync/utils.py
Labels: enhancement

#29 Empty user e-mails.
  src/senaite/sync/importstep.py
Labels: bug

#31 Add changelog, code of conduct and contributing guidelines
  CHANGES.rst
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: enhancement

#25 Import Fails because of removed 'folderish' Content Types.
  src/senaite/sync/fetchstep.py
  src/senaite/sync/importstep.py
  src/senaite/sync/syncstep.py
  src/senaite/sync/utils.py
Labels: bug

#33 'Recover' step in Data Import for failed objects.
  src/senaite/sync/importstep.py
Labels: enhancement

#34 New Complement Step for Migration
  src/senaite/sync/browser/templates/sync.pt
  src/senaite/sync/browser/views.py
  src/senaite/sync/complementstep.py
  src/senaite/sync/fetchstep.py
  src/senaite/sync/syncstep.py
Labels: enhancement

#35 Bug- Complement Step yields all the items.
  CHANGES.rst
  src/senaite/sync/complementstep.py
Labels: bug

#37 Readme and License update
  LICENSE
  README.md
  README.rst
Labels: enhancement
